extends VBoxContainer

@onready var lifeSpanLbl = %lifeSpanLbl
@onready var lifeSpanValueLbl = %lifeSpanValueLbl
@onready var ageLbl = %ageLbl
@onready var ageValueLbl = %ageValueLbl
@onready var hpLbl = %hpLbl
@onready var hpValueLbl = %hpValueLbl
@onready var energyLbl = %energyLbl
@onready var energyValueLbl = %energyValueLbl
@onready var vitalityLbl = %vitalityLbl
@onready var vitalityValueLbl = %vitalityValueLbl
@onready var strengthLbl = %strengthLbl
@onready var strengthValueLbl = %strengthValueLbl
@onready var enduranceValueLbl = %enduranceValueLbl
@onready var agilityLbl = %agilityLbl
@onready var agilityValueLbl = %agilityValueLbl
@onready var constitutionLbl = %constitutionLbl
@onready var constitutionValueLbl = %constitutionValueLbl
@onready var mindLbl = %mindLbl
@onready var mindValueLbl = %mindValueLbl
@onready var intelligenceLbl = %intelligenceLbl
@onready var intelligenceValueLbl = %intelligenceValueLbl
@onready var comprehencionLbl = %comprehencionLbl
@onready var comprehencionValueLbl = %comprehencionValueLbl
@onready var perceptionLbl = %perceptionLbl
@onready var perceptionValueLbl = %perceptionValueLbl
@onready var spiritualSenseLbl = %spiritualSenseLbl
@onready var spiritualSenseValueLbl = %spiritualSenseValueLbl
@onready var willpowerLbl = %willpowerLbl
@onready var willpowerValueLbl = %willpowerValueLbl
@onready var soulSenseLbl = %soulSenseLbl
@onready var soulSenseValueLbl = %soulSenseValueLbl
@onready var charismaLbl = %charismaLbl
@onready var charismaValueLbl = %charismaValueLbl
@onready var insightLbl = %insightLbl
@onready var insightValueLbl = %insightValueLbl
@onready var leadershipLbl = %leadershipLbl
@onready var leadershipValueLbl = %leadershipValueLbl
@onready var potentialLbl = %potentialLbl
@onready var potentialValueLbl = %potentialValueLbl
@onready var destinyLbl = %destinyLbl
@onready var destinyValueLbl = %destinyValueLbl
@onready var luckLbl = %luckLbl
@onready var luckValueLbl = %luckValueLbl

func _process(delta):
	lifeSpanValueLbl.text = str(PlayerCharacterData.stats.lifeSpan)
	ageValueLbl.text = str(PlayerCharacterData.stats.age)
	hpValueLbl.text = str(PlayerCharacterData.stats.currentHP) + " / " + str(PlayerCharacterData.stats.maxHP)
	energyValueLbl.text = str(PlayerCharacterData.stats.currentEnergy) + " / " + str(PlayerCharacterData.stats.maxEnergy)
	vitalityValueLbl.text = str(PlayerCharacterData.stats.vitality)
	strengthValueLbl.text = str(PlayerCharacterData.stats.strength)
	enduranceValueLbl.text = str(PlayerCharacterData.stats.endurance)
	agilityValueLbl.text = str(PlayerCharacterData.stats.agility)
	constitutionValueLbl.text = str(PlayerCharacterData.stats.constitution)
	mindValueLbl.text = str(PlayerCharacterData.stats.mind)
	intelligenceValueLbl.text = str(PlayerCharacterData.stats.intelligence)
	comprehencionValueLbl.text = str(PlayerCharacterData.stats.comprehension)
	perceptionValueLbl.text = str(PlayerCharacterData.stats.perception)
	spiritualSenseValueLbl.text = str(PlayerCharacterData.stats.spiritualSense)
	willpowerValueLbl.text = str(PlayerCharacterData.stats.willpower)
	soulSenseValueLbl.text = str(PlayerCharacterData.stats.soulSense)
	charismaValueLbl.text = str(PlayerCharacterData.stats.charisma)
	insightValueLbl.text = str(PlayerCharacterData.stats.insight)
	leadershipValueLbl.text = str(PlayerCharacterData.stats.leadership)
	potentialValueLbl.text = str(PlayerCharacterData.stats.potential)
	destinyValueLbl.text = str(PlayerCharacterData.stats.destiny)
	luckValueLbl.text = str(PlayerCharacterData.stats.luck)
